import { StyleSheet } from 'react-native';

export const C = {
  bg: '#f7f6fb',
  surface: '#ffffff',
  surface2: '#f0eef7',
  border: '#e4e1f0',
  text: '#1a1728',
  text2: '#6b6886',
  text3: '#a09db8',
  accent: '#7c5cfc',
  green: '#00b894',
  red: '#e17055',
  orange: '#e67e22',
  pink: '#e84393',
} as const;

export const S = StyleSheet.create({
  flex1: { flex: 1 },
  row: { flexDirection: 'row' as const },
  center: { justifyContent: 'center' as const, alignItems: 'center' as const },
  // Backgrounds
  bg: { backgroundColor: C.bg },
  bgSurface: { backgroundColor: C.surface },
  bgSurface2: { backgroundColor: C.surface2 },
  bgAccent: { backgroundColor: C.accent },
  bgAccent15: { backgroundColor: 'rgba(124,92,252,0.15)' },
  bgAccent5: { backgroundColor: 'rgba(124,92,252,0.05)' },
  bgGreen15: { backgroundColor: 'rgba(0,184,148,0.15)' },
  bgRed: { backgroundColor: C.red },
  bgOrange: { backgroundColor: C.orange },
  // Borders
  border: { borderWidth: 1, borderColor: C.border },
  borderAccent: { borderWidth: 1, borderColor: C.accent },
  borderRed: { borderWidth: 2, borderColor: C.red },
  borderDashed: { borderWidth: 2, borderColor: C.border, borderStyle: 'dashed' as const },
  borderBottom: { borderBottomWidth: 1, borderBottomColor: C.border },
  roundedCard: { borderRadius: 12 },
  roundedFull: { borderRadius: 9999 },
  roundedSM: { borderRadius: 8 },
  roundedLg: { borderRadius: 16 },
  // Padding
  p1: { padding: 4 },
  p2: { padding: 8 },
  p3: { padding: 12 },
  p4: { padding: 16 },
  p5: { padding: 20 },
  px4: { paddingHorizontal: 16 },
  px5: { paddingHorizontal: 20 },
  py05: { paddingVertical: 2 },
  py1: { paddingVertical: 4 },
  py2: { paddingVertical: 8 },
  py25: { paddingVertical: 10 },
  py3: { paddingVertical: 12 },
  py4: { paddingVertical: 16 },
  pt3: { paddingTop: 12 },
  pt4: { paddingTop: 16 },
  pb20: { paddingBottom: 80 },
  // Margin
  m05: { margin: 2 },
  m1: { margin: 4 },
  mb1: { marginBottom: 4 },
  mb2: { marginBottom: 8 },
  mb3: { marginBottom: 12 },
  mb4: { marginBottom: 16 },
  mt05: { marginTop: 2 },
  mb05: { marginBottom: 2 },
  mt1: { marginTop: 4 },
  mt2: { marginTop: 8 },
  mt3: { marginTop: 12 },
  mt5: { marginTop: 20 },
  mr3: { marginRight: 12 },
  ml10: { marginLeft: 40 },
  // Gap
  gap1: { gap: 4 },
  gap15: { gap: 6 },
  gap2: { gap: 8 },
  gap3: { gap: 12 },
  gap4: { gap: 16 },
  gap5: { gap: 20 },
  // Text
  textXs: { fontSize: 10 },
  textSm: { fontSize: 13 },
  textBase: { fontSize: 15 },
  textLg: { fontSize: 18 },
  textXl: { fontSize: 20 },
  text2xl: { fontSize: 24 },
  text6xl: { fontSize: 60 },
  text: { color: C.text },
  text2: { color: C.text2 },
  text3: { color: C.text3 },
  textAccent: { color: C.accent },
  textWhite: { color: '#fff' },
  textGreen: { color: C.green },
  textRed: { color: C.red },
  textOrange: { color: C.orange },
  textPink: { color: C.pink },
  semibold: { fontWeight: '600' as const },
  bold: { fontWeight: '700' as const },
  textCenter: { textAlign: 'center' as const },
  leading6: { lineHeight: 24 },
  // Sizes
  w11: { width: 44, height: 44 },
  w14: { width: 56, height: 56 },
  h12: { height: 48 },
  full: { width: '100%' as const },
  max85: { maxWidth: '85%' as const },
  aspect1: { aspectRatio: 1 },
  // Flex
  flexRow: { flexDirection: 'row' as const, alignItems: 'center' as const },
  spaceBetween: { flexDirection: 'row' as const, justifyContent: 'space-between' as const, alignItems: 'center' as const },
  itemsCenter: { alignItems: 'center' as const },
  justifyCenter: { justifyContent: 'center' as const },
  flexWrap: { flexWrap: 'wrap' as const },
  selfEnd: { alignSelf: 'flex-end' as const },
  selfStart: { alignSelf: 'flex-start' as const },
  flex1Row: { flex: 1, flexDirection: 'row' as const, alignItems: 'center' as const },
  // Shadows
  shadow: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 8, elevation: 3 },
  // Chat bubbles
  bubbleUser: {
    alignSelf: 'flex-end' as const,
    maxWidth: '85%' as const,
    backgroundColor: C.accent,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    borderBottomRightRadius: 4,
    marginBottom: 10,
  },
  bubbleAI: {
    alignSelf: 'flex-start' as const,
    maxWidth: '85%' as const,
    backgroundColor: C.surface2,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    borderBottomLeftRadius: 4,
    marginBottom: 10,
  },
});
